name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pytest tests/

  docker-build:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t my-app:latest .

  deploy:
    needs: docker-build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy Application
        run: echo "Deploying application..."

 # Post-deployment steps  
      - name: Wait for Application to Start
        run: sleep 30  # Wait for 30 seconds before checking health status

      - name: Health Check
        run: |
          if curl -s http://your-app-url/health | grep "OK"; then
            echo "Application is healthy!"
          else
            echo "Deployment failed: Health check failed." 
            exit 1
          fi

      - name: Cleanup Unused Docker Images
        run: docker system prune -af

      - name: Notify on Success
        if: success()
        run: echo "Deployment successful! Sending notification..."

      - name: Notify on Failure
        if: failure()
        run: echo "Deployment failed! Alerting team..."